# Loosely based on the following rubocop configurations:
# https://gist.github.com/jhass/a5ae80d87f18e53e7b56
# https://gist.github.com/thomthom/5a08b248ef786cf60ee9e6c3398e21f1

require: rubocop-sketchup

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'tests/**/*'
    - 'tools/**/*'

# This cop catches methods that assigns many variables, even if the complexity
# is low and readability is high.
Metrics/AbcSize:
  Enabled: false

# Short lines are in general good for readability but splitting up one
# expression into multiple lines can be less readable. Aim for 80 chars but
# allow 120.
Metrics/LineLength:
  Max: 120

# Aim for 10 lines and less in each methods but accept slightly longer ones.
Metrics/MethodLength:
  Max: 20

# Modules can be however long that is needed to fit all methods related to the
# corresponding API Class/Module.
Metrics/ModuleLength:
  Enabled: false

Layout/IndentArray:
  EnforcedStyle: consistent

# Use wrapping empty lines in modules containing methods (the first and last
# method should have the same spacing to the module as there are between
# methods).
#
# Don't however use wrapping empty lines for a module that merely wraps another
# module.
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# A module that merely wraps one single direct child module should not be
# indented. Every other code block must be indented.
Layout/IndentationWidth:
  IgnoredPatterns:
    - '^\s*module'

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Conflict too often with Metric/LineLength.
# https://github.com/bbatsov/rubocop/issues/1332#issuecomment-277503854
Style/GuardClause:
  Enabled: false

SketchupDeprecations:
  Enabled: true

SketchupPerformance:
  Enabled: true

SketchupRequirements:
  Enabled: true

SketchupSuggestions:
  Enabled: true

# FileStructure checks don't apply as this isn't an Extension but a library.
SketchupRequirements/FileStructure:
  Enabled: false

# SketchupExtension checks don't apply as this isn't an Extension but a library.
SketchupRequirements/SketchupExtension:
  Enabled: false
